image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:latest

stages:
  - test
  - build
  - deploy

quality:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/thekevjames/nox
  script:
    - nox

build:
  stage: build
  script:
    - pip install build
    - python -m build
  artifacts:
    untracked: false
    expire_in: 1 week
    paths:
      - dist/

publish-gitlab:
  stage: deploy
  script:
    - pip install twine
    - python -m twine check dist/*
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  rules:
    - if: $CI_COMMIT_TAG

publish:
  stage: deploy
  script:
    - pip install twine
    - python -m twine check dist/*
    - python -m twine upload dist/*
  rules:
    - if: $CI_COMMIT_TAG
